version: '3.3'

services:
  postgres:
    image: postgres:14.3
    restart: always
    ports:
      - '5432:5432'
    environment:
       POSTGRES_DB: ${DB_NAME}
       POSTGRES_USER: ${DB_USER}
       POSTGRES_PASSWORD: ${DB_PASSWORD}
    container_name: postgres_db
    volumes:
      - ./postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    environment:
     - PGADMIN_DEFAULT_EMAIL=root@admin.com
     - PGADMIN_DEFAULT_PASSWORD=root
    container_name: pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres
